### ISSUE TITLE
(DOCKER) Missing dependencies: libvips-cpp.so.42 (img: alpine linux (default), hfs latest/0.56)

### ISSUE THREAD

**Issue by Feuerswut** [rejetto/sharp#4]
config:

```
version: '3'

services:
  hfs:
    image: rejetto/hfs
    volumes:
      - "A:/Server-Daten/HFS/CONF:/home/hfs/.hfs" # Shared volume for HFS config
      - "A:/Server-Daten/HFS/DATA:/home/hfs/.hfs/data" # Shared volume for data
    ports:
      - 80:80         # Mapping port X on host to port Y in the container
      - 443:443       # Mapping port X on host to port Y in the container (for HTTPS)
    restart: unless-stopped
```

`
Plugin sharp didn't start, with error: Something went wrong installing the "sharp" module Error loading shared library libvips-cpp.so.42: No such file or directory (needed by /home/hfs/.hfs/plugins/sharp/node_modules/sharp/build/Release/sharp-linuxmusl-x64.node) Possible solutions: - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp" - Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp" - Consult the installation documentation: https://sharp.pixelplumbing.com/install Error: Something went wrong installing the "sharp" module`
